# Generated by Django 5.0 on 2023-12-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_slide',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover',
            field=models.ImageField(null=True, upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_card',
            field=models.ImageField(upload_to='movie_images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(upload_to='movie_videos/'),
        ),
    ]
