# Generated by Django 4.2.8 on 2023-12-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='General',
            new_name='Category',
        ),
    ]
