# Generated by Django 5.0 on 2024-01-01 23:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_movie_image_slide_movie_image_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid1),
        ),
    ]
