# Generated by Django 5.0.1 on 2024-04-25 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_description_latestmovie_overview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='image_card',
            new_name='poster_path',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='length',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_views',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='uu_id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='viewed_ips',
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, upload_to='movie_images/'),
        ),
    ]
