# Generated by Django 5.0.1 on 2024-04-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_description_movie_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.CharField(max_length=255, null=True)),
                ('value', models.BooleanField(default=False)),
            ],
        ),
    ]
