# Generated by Django 5.0 on 2024-01-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic'),
        ('base', '0005_user'),
    ]

    operations = [
    ]
